Changes required for script to run on Python 3.8.1
jilleb/odis2vcp pull request #2
Opened 2020-02-06 23:41 UTC by blackstarxr253

2020-02-06 23:46 UTC, blackstarxr253 commented
The changes were made for the script to run on Windows 10 with Python 3.8.1

2020-02-07 00:15 UTC, blackstarxr253 commented
Also corrects Issue #1

2020-02-07 06:26 UTC, jilleb commented
Great work! 
I'll test and merge asap.
Thanks!

2022-04-04 16:14 UTC, Upgreydd requested changes

2022-04-04 16:14 UTC, Upgreydd commented on odis2vcp.py
>  print ""
This one not converted will make an issue
should be
```
print("")
```

2022-08-25 03:29 UTC, closed without merging